import { useState, useRef, useCallback } from 'react';
import { writeText } from '@tauri-apps/plugin-clipboard-manager';
import { convert_unicode_to_kruti_dev } from '../api/converter';
import './Converter.css';

export function Converter() {
  const [unicodeText, setUnicodeText] = useState('');
  const [krutiDevText, setKrutiDevText] = useState('');
  const [isConverting, setIsConverting] = useState(false);
  const [status, setStatus] = useState<{ type: 'success' | 'error' | 'info'; message: string } | null>(null);
  const krutiDevRef = useRef<HTMLTextAreaElement>(null);

  const handleConvert = useCallback(async () => {
    if (!unicodeText.trim()) {
      setStatus({ type: 'info', message: 'Please enter Unicode Hindi text to convert' });
      return;
    }

    setIsConverting(true);
    setStatus(null);

    try {
      const result = await convert_unicode_to_kruti_dev(unicodeText);
      if (result.success) {
        setKrutiDevText(result.kruti_dev_text);
        setStatus({ type: 'success', message: 'Conversion successful' });
      } else {
        setStatus({ type: 'error', message: result.error || 'Conversion failed' });
      }
    } catch (error) {
      setStatus({ type: 'error', message: 'Conversion failed. Please try again.' });
    } finally {
      setIsConverting(false);
    }
  }, [unicodeText]);

  const handleCopy = useCallback(async () => {
    if (!krutiDevText.trim()) {
      setStatus({ type: 'info', message: 'Nothing to copy. Convert text first.' });
      return;
    }

    try {
      await writeText(krutiDevText);
      setStatus({ type: 'success', message: 'Copied to clipboard!' });
    } catch {
      setStatus({ type: 'error', message: 'Failed to copy to clipboard' });
    }
  }, [krutiDevText]);

  const handleClear = useCallback(() => {
    setUnicodeText('');
    setKrutiDevText('');
    setStatus(null);
  }, []);

  const handlePrint = useCallback(() => {
    if (!krutiDevText.trim()) {
      setStatus({ type: 'info', message: 'Nothing to print. Convert text first.' });
      return;
    }

    const printWindow = window.open('', '_blank');
    if (printWindow) {
      printWindow.document.write(`
        <!DOCTYPE html>
        <html>
        <head>
          <title>SevaDesk - Print</title>
          <style>
            body { font-family: 'Kruti Dev 010', 'Kruti Dev', monospace; font-size: 14px; line-height: 1.6; padding: 40px; }
            .header { text-align: center; margin-bottom: 30px; padding-bottom: 20px; border-bottom: 1px solid #ccc; }
            .header h1 { font-size: 24px; margin-bottom: 8px; }
            .content { white-space: pre-wrap; }
            .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #666; }
            @media print { .no-print { display: none; } }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>SevaDesk</h1>
            <p>Hindi Typing & Forms Library</p>
          </div>
          <div class="content">${krutiDevText.replace(/&/g, '&').replace(/</g, '<').replace(/>/g, '>')}</div>
          <div class="footer">Generated by SevaDesk | Best results: Use Kruti Dev 010 font in MS Word</div>
          <script>window.onload = () => window.print();<\/script>
        </body>
        </html>
      `);
      printWindow.document.close();
    }
  }, [krutiDevText]);

  const handlePaste = useCallback(async () => {
    try {
      const text = await navigator.clipboard.readText();
      setUnicodeText(text);
    } catch {
      setStatus({ type: 'error', message: 'Failed to paste from clipboard' });
    }
  }, []);

  return (
    <div className="converter-page">
      <div className="page-header">
        <h1>Unicode → Kruti Dev Converter</h1>
        <p className="page-subtitle">Convert Hindi Unicode text to Kruti Dev 010 encoding for MS Word</p>
      </div>

      <div className="converter-grid">
        <div className="panel">
          <div className="panel-header">
            <h2>Unicode Hindi</h2>
            <div className="panel-actions">
              <button className="btn btn-ghost btn-sm" onClick={handlePaste} title="Paste from clipboard">
                📋 Paste
              </button>
            </div>
          </div>
          <textarea
            className="panel-textarea"
            value={unicodeText}
            onChange={(e) => setUnicodeText(e.target.value)}
            placeholder="Type or paste Hindi Unicode text here...&#10;&#10;Example: न्यायालय में आवेदन प्रस्तुत है।"
            rows={18}
            spellCheck={false}
          />
          <div className="panel-hint">Supports: Devanagari vowels, consonants, matras, conjuncts, numbers, punctuation</div>
        </div>

        <div className="converter-actions">
          <button
            className="btn btn-primary btn-lg convert-btn"
            onClick={handleConvert}
            disabled={isConverting || !unicodeText.trim()}
          >
            {isConverting ? '⏳ Converting...' : '➤ Convert'}
          </button>
        </div>

        <div className="panel">
          <div className="panel-header">
            <h2>Kruti Dev Output</h2>
            <div className="panel-actions">
              <button className="btn btn-ghost btn-sm" onClick={handleCopy} disabled={!krutiDevText.trim()} title="Copy to clipboard">
                📋 Copy
              </button>
            </div>
          </div>
          <textarea
            ref={krutiDevRef}
            className="panel-textarea kruti-output"
            value={krutiDevText}
            readOnly
            placeholder="Converted Kruti Dev text will appear here..."
            rows={18}
            spellCheck={false}
          />
          <div className="panel-hint">
            <span className="font-note">Best results: Use <strong>Kruti Dev 010</strong> font in MS Word</span>
          </div>
        </div>
      </div>

      <div className="bottom-actions">
        <button className="btn btn-secondary" onClick={handleClear} disabled={!unicodeText.trim() && !krutiDevText.trim()}>
          🗑 Clear All
        </button>
        <button className="btn btn-outline" onClick={handlePrint} disabled={!krutiDevText.trim()}>
          🖨 Print
        </button>
      </div>

      {status && (
        <div className={`status-toast ${status.type}`} role="alert">
          {status.message}
        </div>
      )}

      <div className="converter-info">
        <details>
          <summary>Conversion Details & Supported Features</summary>
          <ul>
            <li><strong>Vowels:</strong> अ आ इ ई उ ऊ ऋ ए ऐ ओ औ</li>
            <li><strong>Consonants:</strong> All 36 Devanagari consonants</li>
            <li><strong>Matras:</strong> ा ि ी ु ू ृ े ै ो ौ</li>
            <li><strong>Special:</strong> Anusvara (ं), Visarga (ः), Virama/halant (्), Candrabindu (ँ)</li>
            <li><strong>Conjuncts:</strong> क्ष, त्र, ज्ञ, श्र (auto-handled)</li>
            <li><strong>Reph/Rakar:</strong> र् handling for half-r forms</li>
            <li><strong>Numbers:</strong> ०-९ → 0-9</li>
            <li><strong>Punctuation:</strong> । ॥</li>
            <li><strong>Output:</strong> Actual Kruti Dev 010 byte encoding (not font change)</li>
          </ul>
        </details>
      </div>
    </div>
  );
}